# Generated by Django 5.2.3 on 2025-07-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_fist_name_order_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='district',
        ),
    ]
